project:
  type: website
  output-dir: docs

website:
  title: "Viswadutt Poduri"
  site-url: https://viswaduttp.github.io/
  description: "Welcome to Viswadutt's Personal Page."
  image: images/default.png
  open-graph: true
  twitter-card: true
  navbar:
    title: Viswadutt's Blog
    right:
      - text: About
        href: About.qmd
      - text: Blog
        href: index.qmd 
      - icon: linkedin
        href: https://www.linkedin.com/in/viswadutt/
      - icon: github
        href: https://github.com/viswaduttp
      - icon: twitter
        href: https://twitter.com/viswadutt
    listing: 
    image-placeholder: images/listing_thumbnail.png
format:
  html:
    theme: 
     light: flatly
     dark: darkly
    css: styles.css
    toc: true
execute:
  freeze: auto
