project:
  type: website
  output-dir: docs

website:
  title: "Viswadutt Poduri"
  site-url: https://viswaduttp.github.io/
  description: "Welcome to Viswadutt's Personal Page."
  navbar:
    right:
      - text: Home
        href: index.qmd
      - text: Blog
        href: blog.qmd 
      - icon: linkedin
        href: https://www.linkedin.com/in/viswadutt/
      - icon: github
        href: https://github.com/viswaduttp
      - icon: twitter
        href: https://twitter.com/viswadutt
format:
  html:
    theme: 
     light: flatly
     dark: darkly
    css: styles.css
    toc: true
execute:
  freeze: auto

